openapi: 3.0.0
info:
  title: Robot API
  version: 1.0.0
paths:
  /robots:
    get:
      summary: Get all robots
      responses:
        '200':
          description: A list of robots
          content:
            application/json:
              example: [{ id: 1, name: 'Robot1', x: 0.0, y: 0.0, theta: 0.0, v: 1.0, ultrasound: 2.0}]
    post:
      summary: Create a new robot
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Robot'
      responses:
        '201':
          description: Robot created successfully
          content:
            application/json:
              example: { id: 1, message: 'Robot created successfully' }
  /robots/{id}:
    get:
      summary: Get a robot by ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the robot
          schema:
            type: integer
      responses:
        '200':
          description: The requested robot
          content:
            application/json:
              example: { id: 1, name: 'Robot1', x: 0.0, y: 0.0, theta: 0.0, v: 1.0, ultrasound: 2.0}
        '404':
          description: Robot not found
    put:
      summary: Update a robot by ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the robot
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Robot'
      responses:
        '200':
          description: Robot updated successfully
          content:
            application/json:
              example: { id: 1, message: 'Robot updated successfully' }
        '404':
          description: Robot not found
    delete:
      summary: Delete a robot by ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the robot
          schema:
            type: integer
      responses:
        '204':
          description: Robot deleted successfully
        '404':
          description: Robot not found
components:
  schemas:
    Robot:
      type: object
      properties:
        id:
          type: integer
        x:
          type: number
          format: double
        y:
          type: number
          format: double
        theta:
          type: number
          format: double
        v:
          type: number
          format: double
        ultrasound:
          type: number
          format: double
